name: Deploy

on:
  # Triggers the workflow on push events for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-
            
      - name: Gatsby Cache
        uses: actions/cache@v2
        with:
          path: ./.cache
          key: gatsby-${{ github.run_id }}
          restore-keys: |
            gatsby-
      
      - name: Install Yarn Dependencies
        run: yarn install

      - name: Build
        run: yarn build --prefix-paths --verbose
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
